name: manage-azure-policy-48f19f44
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Windows_machines_should_meet_requirements_of_the_Azure_compute_security_baseline_72650e9f-97bc-4b2a-ab5f-9781a9fcecbc/**'
#      - .github/workflows/manage-azure-policy-48f19f44.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_48f19f44}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Windows_machines_should_meet_requirements_of_the_Azure_compute_security_baseline_72650e9f-97bc-4b2a-ab5f-9781a9fcecbc/**
