name: manage-azure-policy-0840fecd
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Windows_machines_should_meet_requirements_for_Windows_Firewall_Properties_35d9882c-993d-44e6-87d2-db66ce21b636/**'
#      - .github/workflows/manage-azure-policy-0840fecd.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_0840fecd}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Windows_machines_should_meet_requirements_for_Windows_Firewall_Properties_35d9882c-993d-44e6-87d2-db66ce21b636/**
